spring.application.name=placarbr-api
server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://localhost/placarbr?createDatabaseIfNotExist=true
spring.datasource.username=juninho
spring.datasource.password=juninho11

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:234567}