spring.profiles.active=@activatedProperties@

spring.application.name=placarbr-api
server.servlet.context-path=/api

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:234567}

