name: Deploy Placar Br - Develop

on:
  push:
    branches: [ "develop-gitactions" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests -Dspring.profiles.active=dev
	- name: Login Docker Hub
	  run: docker login -u ${{secrets.DOCKER_USER_NAME}} -p ${{secrets.DOCKER_PASSWORD}}
	- name: Builder docker image
	  run: docker build -t ademirgava/placarbr .
	- name: Push image docker
	  run: docker push ademirgava/placarbr